from djitellopy import tello
from time import sleep
mine = tello.Tello()
mine.connect()
print(mine.get_battery())
mine.takeoff()
sleep(2)
mine.send_rc_control(0,90,0,0)
sleep(2)
mine.send_rc_control(0,-80,0,0)
sleep(2)
mine.send_rc_control(0,0,10,0)
sleep(2)
mine.send_rc_control(0,0,-10,0)
sleep(2)
mine.send_rc_control(0,-90,0,60)
sleep(2)
mine.send_rc_control(0,0,0,0)
mine.land()